<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 6 Capitulo 6 Comparacion de modelos | Análisis de series temporales: Ausentismo laboral</title>
  <meta name="description" content="Este es un ejemplo aplicado de análisis de series temporales usando la base de datos de ausentismo laboral disponible en UCI" />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 6 Capitulo 6 Comparacion de modelos | Análisis de series temporales: Ausentismo laboral" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Este es un ejemplo aplicado de análisis de series temporales usando la base de datos de ausentismo laboral disponible en UCI" />
  <meta name="github-repo" content="https://github.com/rortizgeo/TS_bookdown" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 6 Capitulo 6 Comparacion de modelos | Análisis de series temporales: Ausentismo laboral" />
  
  <meta name="twitter:description" content="Este es un ejemplo aplicado de análisis de series temporales usando la base de datos de ausentismo laboral disponible en UCI" />
  

<meta name="author" content="Ricardo Ortiz; Jaime Martinez, Jeisson Rodriguez" />


<meta name="date" content="2025-06-02" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelo-prophet.html"/>
<link rel="next" href="references.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/dygraphs-1.1.1/dygraph.css" rel="stylesheet" />
<script src="libs/dygraphs-1.1.1/dygraph-combined.js"></script>
<script src="libs/dygraphs-1.1.1/shapes.js"></script>
<script src="libs/moment-2.8.4/moment.js"></script>
<script src="libs/moment-timezone-0.2.5/moment-timezone-with-data.js"></script>
<script src="libs/moment-fquarter-1.0.0/moment-fquarter.min.js"></script>
<script src="libs/dygraphs-binding-1.1.1.6/dygraphs.js"></script>
<script src="libs/Dygraph.Plugins.Unzoom-1.0/unzoom.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.33/datatables.js"></script>
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.13.6/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.13.6/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>
<script src="libs/plotly-binding-4.10.4/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Análisis de series temporales</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="ausentismo-laboral.html"><a href="ausentismo-laboral.html"><i class="fa fa-check"></i><b>1</b> AUSENTISMO LABORAL</a>
<ul>
<li class="chapter" data-level="1.1" data-path="ausentismo-laboral.html"><a href="ausentismo-laboral.html#introducción"><i class="fa fa-check"></i><b>1.1</b> Introducción</a></li>
<li class="chapter" data-level="1.2" data-path="ausentismo-laboral.html"><a href="ausentismo-laboral.html#finalidad-del-estudio"><i class="fa fa-check"></i><b>1.2</b> Finalidad del estudio</a></li>
<li class="chapter" data-level="1.3" data-path="ausentismo-laboral.html"><a href="ausentismo-laboral.html#diseño-del-estudio"><i class="fa fa-check"></i><b>1.3</b> Diseño del estudio</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html"><i class="fa fa-check"></i><b>2</b> Análisis de los datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#media-movil"><i class="fa fa-check"></i><b>2.1</b> Media Movil</a></li>
<li class="chapter" data-level="2.2" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#rezagos"><i class="fa fa-check"></i><b>2.2</b> Rezagos</a></li>
<li class="chapter" data-level="2.3" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#análísis-de-estacionalidad"><i class="fa fa-check"></i><b>2.3</b> Análísis de estacionalidad</a></li>
<li class="chapter" data-level="2.4" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#descomposición-de-la-serie-temporal"><i class="fa fa-check"></i><b>2.4</b> Descomposición de la serie temporal</a></li>
<li class="chapter" data-level="2.5" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#estacionariedad"><i class="fa fa-check"></i><b>2.5</b> Estacionariedad</a></li>
<li class="chapter" data-level="2.6" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#diferenciación"><i class="fa fa-check"></i><b>2.6</b> Diferenciación</a></li>
<li class="chapter" data-level="2.7" data-path="análisis-de-los-datos.html"><a href="análisis-de-los-datos.html#conclusión"><i class="fa fa-check"></i><b>2.7</b> Conclusión</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="predicciones.html"><a href="predicciones.html"><i class="fa fa-check"></i><b>3</b> Predicciones</a>
<ul>
<li class="chapter" data-level="3.1" data-path="predicciones.html"><a href="predicciones.html#método-holt-winters"><i class="fa fa-check"></i><b>3.1</b> Método Holt-Winters</a></li>
<li class="chapter" data-level="3.2" data-path="predicciones.html"><a href="predicciones.html#predicción-próximos-7-días"><i class="fa fa-check"></i><b>3.2</b> Predicción próximos 7 días</a></li>
<li class="chapter" data-level="3.3" data-path="predicciones.html"><a href="predicciones.html#conclusión-aplicacion-metodología-holt-winters"><i class="fa fa-check"></i><b>3.3</b> Conclusión aplicacion metodología Holt-Winters</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="modelo-arima.html"><a href="modelo-arima.html"><i class="fa fa-check"></i><b>4</b> Modelo ARIMA</a>
<ul>
<li class="chapter" data-level="4.1" data-path="modelo-arima.html"><a href="modelo-arima.html#generación-del-modelo"><i class="fa fa-check"></i><b>4.1</b> Generación del modelo</a></li>
<li class="chapter" data-level="4.2" data-path="modelo-arima.html"><a href="modelo-arima.html#análisis-de-los-residuos"><i class="fa fa-check"></i><b>4.2</b> Análisis de los residuos</a></li>
<li class="chapter" data-level="4.3" data-path="modelo-arima.html"><a href="modelo-arima.html#punto-de-cambio-amoc"><i class="fa fa-check"></i><b>4.3</b> Punto de cambio (AMOC)</a></li>
<li class="chapter" data-level="4.4" data-path="modelo-arima.html"><a href="modelo-arima.html#predicción"><i class="fa fa-check"></i><b>4.4</b> Predicción</a></li>
<li class="chapter" data-level="4.5" data-path="modelo-arima.html"><a href="modelo-arima.html#conclusiones"><i class="fa fa-check"></i><b>4.5</b> Conclusiones</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="modelo-prophet.html"><a href="modelo-prophet.html"><i class="fa fa-check"></i><b>5</b> Modelo Prophet</a>
<ul>
<li class="chapter" data-level="5.1" data-path="modelo-prophet.html"><a href="modelo-prophet.html#generacion-del-modelo"><i class="fa fa-check"></i><b>5.1</b> Generacion del modelo</a></li>
<li class="chapter" data-level="5.2" data-path="modelo-prophet.html"><a href="modelo-prophet.html#predicción-1"><i class="fa fa-check"></i><b>5.2</b> Predicción</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="capitulo-6-comparacion-de-modelos.html"><a href="capitulo-6-comparacion-de-modelos.html"><i class="fa fa-check"></i><b>6</b> Capitulo 6 Comparacion de modelos</a>
<ul>
<li class="chapter" data-level="6.1" data-path="capitulo-6-comparacion-de-modelos.html"><a href="capitulo-6-comparacion-de-modelos.html#métricas-a-implementar"><i class="fa fa-check"></i><b>6.1</b> Métricas a implementar</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="chapter" data-level="7" data-path="redes-neuronales.html"><a href="redes-neuronales.html"><i class="fa fa-check"></i><b>7</b> Redes Neuronales</a>
<ul>
<li class="chapter" data-level="7.1" data-path="redes-neuronales.html"><a href="redes-neuronales.html#redes-neuronales-elman"><i class="fa fa-check"></i><b>7.1</b> Redes neuronales: ELMAN</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="redes-neuronales.html"><a href="redes-neuronales.html#desempeño-del-modelo-elman-con-datos-de-entrenamiento."><i class="fa fa-check"></i><b>7.1.1</b> Desempeño del modelo ELMAN con datos de entrenamiento.</a></li>
<li class="chapter" data-level="7.1.2" data-path="redes-neuronales.html"><a href="redes-neuronales.html#desempeño-del-modelo-elman-con-datos-de-prueba."><i class="fa fa-check"></i><b>7.1.2</b> Desempeño del modelo ELMAN con datos de prueba.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="redes-neuronales.html"><a href="redes-neuronales.html#redes-neuronales-jordan"><i class="fa fa-check"></i><b>7.2</b> Redes neuronales: JORDAN</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="redes-neuronales.html"><a href="redes-neuronales.html#desempeño-del-modelo-jordan-con-datos-de-entrenamiento."><i class="fa fa-check"></i><b>7.2.1</b> Desempeño del modelo JORDAN con datos de entrenamiento.</a></li>
<li class="chapter" data-level="7.2.2" data-path="redes-neuronales.html"><a href="redes-neuronales.html#desempeño-del-modelo-jordan-con-datos-de-prueba."><i class="fa fa-check"></i><b>7.2.2</b> Desempeño del modelo JORDAN con datos de prueba.</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="redes-neuronales.html"><a href="redes-neuronales.html#rendimiento-redes-elman-y-jordan"><i class="fa fa-check"></i><b>7.3</b> Rendimiento Redes ELMAN y JORDAN</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="redes-neuronales.html"><a href="redes-neuronales.html#rendimiento-elman"><i class="fa fa-check"></i><b>7.3.1</b> Rendimiento ELMAN</a></li>
<li class="chapter" data-level="7.3.2" data-path="redes-neuronales.html"><a href="redes-neuronales.html#rendimiento-jordan"><i class="fa fa-check"></i><b>7.3.2</b> Rendimiento Jordan</a></li>
<li class="chapter" data-level="7.3.3" data-path="redes-neuronales.html"><a href="redes-neuronales.html#conclusión-1"><i class="fa fa-check"></i><b>7.3.3</b> Conclusión</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rortizgeo/TS_bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Análisis de series temporales: Ausentismo laboral</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="capitulo-6-comparacion-de-modelos" class="section level1 hasAnchor" number="6">
<h1><span class="header-section-number">Capítulo 6</span> Capitulo 6 Comparacion de modelos<a href="capitulo-6-comparacion-de-modelos.html#capitulo-6-comparacion-de-modelos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Para evaluar el desempeño de distintos enfoques en la predicción del ausentismo laboral, se realizó una comparación entre tres modelos ampliamente utilizados en series de tiempo: ARIMA, ETS (suavizamiento exponencial) y Prophet. Cada uno de estos modelos incorpora supuestos y mecanismos distintos para capturar patrones como la tendencia, la estacionalidad y la variabilidad residual. El objetivo de esta comparación es identificar cuál de ellos ofrece mejores capacidades de ajuste y predicción a partir de los datos históricos disponibles. Para ello, se utilizó un conjunto de entrenamiento con datos diarios, y se aplicaron métricas de desempeño como el RMSE y MAE, además de visualizar sus pronósticos para un horizonte de tres meses. Esta evaluación permite establecer fortalezas y limitaciones relativas de cada enfoque, facilitando una selección informada del modelo más adecuado según el contexto y los objetivos analíticos.</p>
<div id="métricas-a-implementar" class="section level2 hasAnchor" number="6.1">
<h2><span class="header-section-number">6.1</span> Métricas a implementar<a href="capitulo-6-comparacion-de-modelos.html#métricas-a-implementar" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para la comparación de modelos se utilizan las siguientes métricas:</p>
<ul>
<li><p><em>Error medio (ME – Mean Error)</em> : Es el promedio de todos los errores de un conjunto de observaciones.Puede estar sesgada debido ala compensacion de errores positivos y negativos pero sirve como indicador de asimetrias en la distribucion de los errores</p></li>
<li><p><em>La raíz del error cuadrático medio (RMSE – Root Mean Square Error)</em>: Es la desviación estándar de los errores y tiene la ventaja de tener las mismas unidades que la variable predicha, por lo que es más fácil de interpretar directamente.</p></li>
<li><p><em>Error absoluto medio (MAE – Mean Absolute Error)</em>: Corrige la inexactitud del error medio al poseeer valores absolutos, da un promedio de la magnitud absoluta de todos los valores de los errores, sin importar si eran positivos o negativos.protege los valorrs atipicos</p></li>
<li><p><em>Error porcentual medio (MPE – Mean Percentage Error )</em>: Es el promedio de errores porcentuales por los que cada previsión difiere de sus correspondientes valores reales observados y no es una metrica adecuada para conjuntos de datos que contienen valores observados iguales a cero</p></li>
<li><p><em>Error porcentual absoluto medio (MAPE – Mean Absolute Percentage Error)</em>: Esta metrica arregla el problema con la compensación de errores como lo hace el MAE pero funciona mejor si no hay extremos en los datos y no hay ceros.</p></li>
<li><p><em>Error cuadrático medio (MASE – Mean Square Error)</em>: Corrige tambien las inexactitudes del error medio y comparado con el MAE otorga una mayor penalización en los errores de predicción grandes.</p></li>
<li><p><em>Autocorrelacion (ACF1)</em>: Es un coeficiente de correlacion entre una observacion actual y sus valores retardados en distintos momentos. Mide la similitud entre la observacion actual y sus valores pasados, indicando la presencia de patrones o tendencias repetitivos en los datos.</p></li>
</ul>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="capitulo-6-comparacion-de-modelos.html#cb64-1" tabindex="-1"></a><span class="co"># Asegurarse que los datos tienen las columnas ds (fecha)  y (valor)</span></span>
<span id="cb64-2"><a href="capitulo-6-comparacion-de-modelos.html#cb64-2" tabindex="-1"></a><span class="co"># Convertir el ts a tsibble para que pueda ser usado con la librería fable</span></span>
<span id="cb64-3"><a href="capitulo-6-comparacion-de-modelos.html#cb64-3" tabindex="-1"></a>ts_diaria <span class="ot">&lt;-</span> <span class="fu">as_tsibble</span>(serie_diaria, <span class="at">index =</span> ds)</span>
<span id="cb64-4"><a href="capitulo-6-comparacion-de-modelos.html#cb64-4" tabindex="-1"></a></span>
<span id="cb64-5"><a href="capitulo-6-comparacion-de-modelos.html#cb64-5" tabindex="-1"></a><span class="co"># Filtrar datos solo del año 2007 si fuera necesario (opcional si ya está limpio)</span></span>
<span id="cb64-6"><a href="capitulo-6-comparacion-de-modelos.html#cb64-6" tabindex="-1"></a>ts_diaria <span class="ot">&lt;-</span> ts_diaria <span class="sc">%&gt;%</span></span>
<span id="cb64-7"><a href="capitulo-6-comparacion-de-modelos.html#cb64-7" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="fu">year</span>(ds) <span class="sc">==</span> <span class="dv">2007</span>)</span>
<span id="cb64-8"><a href="capitulo-6-comparacion-de-modelos.html#cb64-8" tabindex="-1"></a></span>
<span id="cb64-9"><a href="capitulo-6-comparacion-de-modelos.html#cb64-9" tabindex="-1"></a><span class="co"># Dividir el conjunto: entrenamiento (enero a septiembre), test (octubre a diciembre)</span></span>
<span id="cb64-10"><a href="capitulo-6-comparacion-de-modelos.html#cb64-10" tabindex="-1"></a>train <span class="ot">&lt;-</span> ts_diaria <span class="sc">%&gt;%</span></span>
<span id="cb64-11"><a href="capitulo-6-comparacion-de-modelos.html#cb64-11" tabindex="-1"></a>  <span class="fu">filter</span>(ds <span class="sc">&lt;</span> <span class="fu">ymd</span>(<span class="st">&quot;2007-10-01&quot;</span>))</span>
<span id="cb64-12"><a href="capitulo-6-comparacion-de-modelos.html#cb64-12" tabindex="-1"></a></span>
<span id="cb64-13"><a href="capitulo-6-comparacion-de-modelos.html#cb64-13" tabindex="-1"></a>test <span class="ot">&lt;-</span> ts_diaria <span class="sc">%&gt;%</span></span>
<span id="cb64-14"><a href="capitulo-6-comparacion-de-modelos.html#cb64-14" tabindex="-1"></a>  <span class="fu">filter</span>(ds <span class="sc">&gt;=</span> <span class="fu">ymd</span>(<span class="st">&quot;2007-10-01&quot;</span>))</span>
<span id="cb64-15"><a href="capitulo-6-comparacion-de-modelos.html#cb64-15" tabindex="-1"></a></span>
<span id="cb64-16"><a href="capitulo-6-comparacion-de-modelos.html#cb64-16" tabindex="-1"></a><span class="co"># Ajustar los modelos con los datos de entrenamiento</span></span>
<span id="cb64-17"><a href="capitulo-6-comparacion-de-modelos.html#cb64-17" tabindex="-1"></a>fit <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb64-18"><a href="capitulo-6-comparacion-de-modelos.html#cb64-18" tabindex="-1"></a>  <span class="fu">model</span>(</span>
<span id="cb64-19"><a href="capitulo-6-comparacion-de-modelos.html#cb64-19" tabindex="-1"></a>    <span class="at">arima =</span> <span class="fu">ARIMA</span>(y),</span>
<span id="cb64-20"><a href="capitulo-6-comparacion-de-modelos.html#cb64-20" tabindex="-1"></a>    <span class="at">ets =</span> <span class="fu">ETS</span>(y),</span>
<span id="cb64-21"><a href="capitulo-6-comparacion-de-modelos.html#cb64-21" tabindex="-1"></a>    <span class="at">prophet =</span> <span class="fu">prophet</span>(y <span class="sc">~</span> <span class="fu">season</span>(<span class="st">&quot;week&quot;</span>))</span>
<span id="cb64-22"><a href="capitulo-6-comparacion-de-modelos.html#cb64-22" tabindex="-1"></a>  )</span></code></pre></div>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="capitulo-6-comparacion-de-modelos.html#cb65-1" tabindex="-1"></a><span class="co"># Predecir el mismo horizonte que test (ej: 92 días para octubre-diciembre)</span></span>
<span id="cb65-2"><a href="capitulo-6-comparacion-de-modelos.html#cb65-2" tabindex="-1"></a>forecast_fit <span class="ot">&lt;-</span> <span class="fu">forecast</span>(fit, <span class="at">h =</span> <span class="fu">nrow</span>(test))</span>
<span id="cb65-3"><a href="capitulo-6-comparacion-de-modelos.html#cb65-3" tabindex="-1"></a></span>
<span id="cb65-4"><a href="capitulo-6-comparacion-de-modelos.html#cb65-4" tabindex="-1"></a><span class="co"># Visualizar comparación entre predicción y datos reales</span></span>
<span id="cb65-5"><a href="capitulo-6-comparacion-de-modelos.html#cb65-5" tabindex="-1"></a><span class="fu">autoplot</span>(forecast_fit, ts_diaria) <span class="sc">+</span></span>
<span id="cb65-6"><a href="capitulo-6-comparacion-de-modelos.html#cb65-6" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Comparación de modelos: predicción vs. datos reales&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/unnamed-chunk-40-1.png" width="672" /></p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="capitulo-6-comparacion-de-modelos.html#cb66-1" tabindex="-1"></a>accuracy_table <span class="ot">&lt;-</span> forecast<span class="sc">::</span><span class="fu">accuracy</span>(forecast_fit, test)</span>
<span id="cb66-2"><a href="capitulo-6-comparacion-de-modelos.html#cb66-2" tabindex="-1"></a><span class="fu">print</span>(accuracy_table)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 10
##   .model  .type     ME  RMSE   MAE   MPE  MAPE  MASE RMSSE    ACF1
##   &lt;chr&gt;   &lt;chr&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;
## 1 arima   Test   1.40   26.7  12.8  -Inf   Inf   NaN   NaN -0.0640
## 2 ets     Test   2.19   25.7  12.2   NaN   Inf   NaN   NaN -0.127 
## 3 prophet Test  -0.613  25.6  12.4   NaN   Inf   NaN   NaN -0.131</code></pre>
<div id="conclusiones-1" class="section level4 hasAnchor" number="6.1.0.1">
<h4><span class="header-section-number">6.1.0.1</span> Conclusiones<a href="capitulo-6-comparacion-de-modelos.html#conclusiones-1" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>Al comparar el desempeño de los modelos ARIMA, ETS y Prophet sobre el conjunto de prueba (octubre a diciembre de 2007), se observa que los tres modelos presentan errores similares en términos absolutos, aunque con algunas diferencias relevantes en su comportamiento. El modelo Prophet mostró el menor RMSE (25.6), lo que indica que, en promedio, sus errores más grandes fueron ligeramente menos severos que los de ETS (25.7) y ARIMA (26.7). En términos de MAE, el modelo ETS obtuvo el mejor desempeño (12.2), seguido muy de cerca por Prophet (12.4), mientras que ARIMA presentó el mayor error absoluto promedio (12.8), lo que lo posiciona como el modelo menos preciso en esta comparación.</p>
<p>En cuanto al sesgo de las predicciones (ME), ARIMA y ETS tienden a sobreestimar los valores reales (ME positivo), mientras que Prophet mostró un leve sesgo negativo, indicando una ligera tendencia a subestimar las observaciones. No obstante, este sesgo en Prophet es pequeño y posiblemente no significativo en la práctica.</p>
<p>Por otro lado, las métricas de error basadas en porcentajes (MPE y MAPE) y las escaladas respecto a modelos base (MASE y RMSSE) no son confiables en este caso por contar con valores reales iguales a cero, razón por la que muestran valores indefinidos (NaN) o infinitos (Inf). Esto afecta la estabilidad numérica de estas métricas. Para este tipo de series, se recomienda complementar con otras métricas como SMAPE o enfocarse en MAE y RMSE.</p>
<p>Finalmente, el análisis de la autocorrelación de los residuos (ACF1) muestra que los tres modelos presentan valores cercanos a cero, lo cual sugiere que no hay una estructura significativa de autocorrelación en los errores, lo que es un buen indicio de adecuación del modelo.</p>
<p>Aunque todos los modelos ofrecen un desempeño razonablemente similar, ETS y Prophet destacan como las mejores opciones para este caso específico, con Prophet ofreciendo un balance adecuado entre bajo error cuadrático medio y menor sesgo.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelo-prophet.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rortizgeo/TS_bookdown/05-Prophet.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
